In [5]:
import json
import pandas as pd

In [ ]:
with open('../data/ner_result.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

{'7406': {'index': 7406, 'original_text': '#신림카페#사장님센스굿#레몬청#카페맛집#수제카페#먹스타그램#먹부림#갬성#인스타맛집직접 수제로 만든 청과 디저트라서 더 담백하고 새콤달콤해요. 맛 보시면 사장님 정성 다 느껴집니다ㅎ꼭 한번 방문해보세요^^', 'ner_tags': {'MENU': [{'entity': '레몬청', 'descriptor': '담백하고 새콤달콤하다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2767': {'index': 2767, 'original_text': '커피가 연하고 맛있어용 ㅎ 강아지가 반겨줘요 ㅎ', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2766': {'index': 2766, 'original_text': '사장님도 친절하시고 강아지랑 같이 왓는데 비숑들이 반겨줘서 좋앗습니다!맛잇어요~', 'ner_tags': {'MENU': [{'entity': '맛', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '강아지', 'descriptor': '좋다', 'sentiment': '긍정'}]}}, '2768': {'index': 2768, 'original_text': '오늘도 만족합니다! 어제리뷰써서 서비스 샐러드 받아서 먹었는데 오 맛있더라구요 여자친구도 맛있다고 그러더라구요 그래서 조심스럽게 사장님에게 더받을수있냐고 여쭤봤는데 된다고 하셔서요ㅠ 감사합니다! 마지막은 귀여운 강아지들이 잘가라고 앞에까지 나오네요ㅎ', 'ner_tags': {'MENU': [{'entity': '샐러드', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '여자친구', 'descriptor': '맛있다고 하다', 'sentiment': '긍정'}]}}, '7407': {'index': 7407, 'original_text': '쿠앤크케이크 먹어봤는데 너무 맛있어요 정말맛집이라서 맨날맨날 갈거에여', 'ner_tags': {'MENU': [{'entity': '쿠앤크케이크', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12051': {'index': 12051, 'original_text': '공사할때부터 기대했는데 가게 인테리어가 아늑하고 넘 예뻐요 모크커피 모크크림커피가 시그니처 메뉴인것같아서 마셔봤는데 너무맛있어서 비결이 뭐냐고 물어볼뻔했네요ㅠ 사장님도 친절하시고 넘좋아요 주말마다 가고싶어요', 'ner_tags': {'MENU': [{'entity': '모크커피', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '모크크림커피', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [{'entity': '인테리어', 'descriptor': '아늑하다', 'sentiment': '긍정'}], 'ATMOSPHERE': [], 'TARGET': [{'entity': '주말마다 가고싶다', 'descriptor': None, 'sentiment': '긍정'}]}}, '12050': {'index': 12050, 'original_text': '시그니처가 커피는 커피대로 크림은 크림대로 맛있는데 둘의 하모니 최고. 적당히 달달해서 계속 들어감. 레몬머틀티는 향도 좋고 맛은 개인적으로 두번째 우렸을때가 더 맛있었습니다. 추울때 카페인 없는 음료로 아주 제격.', 'ner_tags': {'MENU': [{'entity': '시그니처 커피', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '레몬머틀티', 'descriptor': '향이 좋다', 'sentiment': '긍정'}, {'entity': '레몬머틀티', 'descriptor': '두번째 우렸을때 더 맛있다', 'sentiment': '긍정'}, {'entity': '카페인 없는 음료', 'descriptor': '아주 제격이다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12052': {'index': 12052, 'original_text': '카페가 완젼 귀여워요 ! 커피도 진하고 고소해서 디저트랑같이 먹으니까 넘 잘 어울려요! 사장님도 친절하시고~앞으로 자주 오게 될 거 같애요!', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '진하고 고소하다', 'sentiment': '긍정'}], 'FACILITY': [{'entity': '카페', 'descriptor': '귀엽다', 'sentiment': '긍정'}], 'ATMOSPHERE': [], 'TARGET': []}}, '2769': {'index': 2769, 'original_text': '오늘도 방문해서 러스크랑 샐러드 서비스 받았어요~자주방문할거같아요~!', 'ner_tags': {'MENU': [{'entity': '러스크', 'descriptor': None, 'sentiment': '중립'}, {'entity': '샐러드', 'descriptor': None, 'sentiment': '중립'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7408': {'index': 7408, 'original_text': '#오레오#케이크#슬지로운생활오늘은 오레오케이크가 나왔다해서 먹어봤는데 안에 오레오 들어간 것도 많고 위에 오레오가 올라가있어서 맛있었어요 ㅎ', 'ner_tags': {'MENU': [{'entity': '오레오케이크', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2771': {'index': 2771, 'original_text': '가성비가 최고입니다 추천이요', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7409': {'index': 7409, 'original_text': '오레오 치즈케이크 신상이라고 해서 먹어봤는데 가격도 저렴라고 아메리카노랑 같이 먹으니까 너무 맛있네요 소량으로 판매하는게 아쉬워요 사장님 자주 만들어주세요~', 'ner_tags': {'MENU': [{'entity': '오레오 치즈케이크', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '아메리카노', 'descriptor': None, 'sentiment': '중립'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '소량으로 판매하는게 아쉬워요', 'descriptor': '아쉽다', 'sentiment': '부정'}]}}, '2770': {'index': 2770, 'original_text': '1리터 아메리카노 테이크아웃이 1900원 이라길래 처음 방문했는데 진짜였어요!. 사장님도 친절하시고 처음방문한지라 러스크도 서비스로 주셨어요 커피도 맛있어요!. 가성비 굿', 'ner_tags': {'MENU': [{'entity': '아메리카노', 'descriptor': '가격이 1900원이다', 'sentiment': '중립'}, {'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '가성비', 'descriptor': '굿', 'sentiment': '긍정'}]}}, '7410': {'index': 7410, 'original_text': '신상 오레오 치즈 케이크 먹어봤는데 5000원밖에 안하고 다른곳 케이크보다 싸고 양도 많고 입에 단맛이 남지 않아서 좋은거 같아요 일주일에 한두번 소량으로 판매하신다는데 메뉴판에 올라와있을때 바로 사 드세요ㅎ 언제 다 팔릴지 모릅니다!', 'ner_tags': {'MENU': [{'entity': '오레오 치즈 케이크', 'descriptor': '가격이 싸다', 'sentiment': '긍정'}, {'entity': '오레오 치즈 케이크', 'descriptor': '양이 많다', 'sentiment': '긍정'}, {'entity': '오레오 치즈 케이크', 'descriptor': '입에 단맛이 남지 않는다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12053': {'index': 12053, 'original_text': "근처에 새로 생겨서 처음으로 가봤는데, Oh my gosh Is it a real?커피가 너무 맛있고 무엇보다 새로 오픈하셔서 매장도 깨끗하고, 좌석이 너무 편했어요! 가끔 카페에 가면 좌석이 불편해서 기분이 별로일때가 있는데, 좌석이 너무 편해서 여자친구랑 얘기하기에 너무좋았어요!조명도 간접조명이어서 눈도 편하고 제일 좋았던점은 first of all! It's the cafe owner! She is so kind and polite사장님이 너무 친절하셔서 그게 제일 좋았어요!", 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [{'entity': '매장', 'descriptor': '깨끗하다', 'sentiment': '긍정'}, {'entity': '좌석', 'descriptor': '편하다', 'sentiment': '긍정'}, {'entity': '조명', 'descriptor': '눈이 편하다', 'sentiment': '긍정'}], 'ATMOSPHERE': [], 'TARGET': [{'entity': '얘기하기', 'descriptor': '좋다', 'sentiment': '긍정'}]}}, '7411': {'index': 7411, 'original_text': '수박쥬스 너무 맛있어요~!동네에 카페가 많아서 근처 카페들을 탐방하러 갔다가 오랜만에 정말 마음에 드는 카페를 찾은 느낌이에요! 사장님도 센스도 있고 매장 분위기도 정말 좋아서 덕분에 잘 마시고 잘 쉬다가 가요!', 'ner_tags': {'MENU': [{'entity': '수박쥬스', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [{'entity': '매장 분위기', 'descriptor': '좋다', 'sentiment': '긍정'}], 'TARGET': []}}, '7412': {'index': 7412, 'original_text': '다른곳보다 저렴하고 맛있어서요즘 즐겨가는 카페입니다.ㅎ', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '카페', 'descriptor': '저렴하고 맛있다', 'sentiment': '긍정'}]}}, '12054': {'index': 12054, 'original_text': '커피가 정말 맛있네요.! 풍미가 진하고 핸드메이드 디저트 류가 너무 맛있어요 ㅠ 가까우면 매일 가고 싶은 카페 당첨이에요 무조건! 따뜻하고 아늑한 분위기가 좋습니다 추천해요', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '핸드메이드 디저트 류', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [{'entity': '따뜻하고 아늑한 분위기', 'descriptor': '좋다', 'sentiment': '긍정'}], 'TARGET': [{'entity': '카페', 'descriptor': '가고 싶다', 'sentiment': '긍정'}]}}, '2773': {'index': 2773, 'original_text': '사장님이 친절하고 커피가 저렴해요!', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '저렴하다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2774': {'index': 2774, 'original_text': '항상 맛있어요매번 마시러 오는 캘리진짜 찐이에요강아지도 넘나 귀여워요', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2772': {'index': 2772, 'original_text': '사장님이 넘 친절하시고~커피랑 브런치가 고퀄리티 합니다갓구운 빵맛이 끝내줍니다 담에 가족들하고 외식하러와야겠어요', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '고퀄리티', 'sentiment': '긍정'}, {'entity': '브런치', 'descriptor': '고퀄리티', 'sentiment': '긍정'}, {'entity': '빵', 'descriptor': '맛이 끝내준다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '가족들', 'descriptor': '외식하러 와야겠다', 'sentiment': '긍정'}]}}, '7414': {'index': 7414, 'original_text': '술지로운생활 너무 맛있어요! 여기만 갈거에요! 올여름은 슬지로운 생활!', 'ner_tags': {'MENU': [{'entity': '술지로운생활', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7413': {'index': 7413, 'original_text': '신메뉴 수박주스 시원하고 맛있네요 혼자 살아서 과일 사먹기 힘든데 종종 사먹을거 같아요', 'ner_tags': {'MENU': [{'entity': '수박주스', 'descriptor': '시원하고 맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '혼자', 'descriptor': None, 'sentiment': '중립'}]}}, '12055': {'index': 12055, 'original_text': '따뜻하고 귀여운 분위기가 너무 좋은 곳이였어요 시그니처 메뉴인 모크커피를 마셨는데 기분 좋은 달달함에 부드러운 우유와 진한 에스프레소가 어우러져 정말 순삭이였어요.당일 구우신 로투스피칸 휘낭시에는 겉은 바삭하고 안은 촉촉하니 버터향이 가득하여 정말 백개는 먹을 수 있을 정도였습니다… 앞으로 자주 갈게요! 모크커피 대박나세요!', 'ner_tags': {'MENU': [{'entity': '모크커피', 'descriptor': '기분 좋은 달달함에 부드러운 우유와 진한 에스프레소가 어우러져 순삭이다', 'sentiment': '긍정'}, {'entity': '로투스피칸 휘낭시네', 'descriptor': '겉은 바삭하고 안은 촉촉하니 버터향이 가득하다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [{'entity': '따뜻하고 귀여운 분위기', 'descriptor': '좋다', 'sentiment': '긍정'}], 'TARGET': []}}, '12058': {'index': 12058, 'original_text': '라떼가 진하고 맛있어요', 'ner_tags': {'MENU': [{'entity': '라떼', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2775': {'index': 2775, 'original_text': '저렴하고 양도 많고 간식도 무료로 주고 너무 좋습니다 추천합니다', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '추천', 'descriptor': None, 'sentiment': '긍정'}]}}, '2776': {'index': 2776, 'original_text': '가격도 너무 저렴하고 맛있습니다 추천이요 ㅋ', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12056': {'index': 12056, 'original_text': '좌석도 많고 사장님 너무 친절하세요강아지들 먹을수있는 물통도 준비해더라고요!디저트랑 음료는 당연 맛있습니다', 'ner_tags': {'MENU': [{'entity': '디저트', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [{'entity': '좌석', 'descriptor': '많다', 'sentiment': '긍정'}, {'entity': '물통', 'descriptor': None, 'sentiment': '중립'}], 'ATMOSPHERE': [], 'TARGET': []}}, '12061': {'index': 12061, 'original_text': '맛있게 잘 마셨어요', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7417': {'index': 7417, 'original_text': '하루에 한잔 안먹으면 손이 떨려요.제발 가서 한잔만 드셔보세요^^ 다른곳 못갑니다장담해요 가격대비 가성비 굿굿굿#대학동커피#슬지로운생활#대학동맛집', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12060': {'index': 12060, 'original_text': '자주 가는 동네 까페, 커피, 음료가 맛있어서 좋아요', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7416': {'index': 7416, 'original_text': '케이크 너무 맛있어요 음료도 너무 맛있구요!', 'ner_tags': {'MENU': [{'entity': '케이크', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2777': {'index': 2777, 'original_text': '날이 좋아서 밖에서 먹으려고 포장했어요ㅎ샐러드도 서비스로 주시고 감사해요 남자친구가 커피입맛 까다로운데 깔끔하고 맛있대요 집 근처라 자주 방문할게요~', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '깔끔하고 맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '자주 방문', 'descriptor': None, 'sentiment': '긍정'}]}}, '12057': {'index': 12057, 'original_text': '따스한 분위기의 카페 조용히 독서하고싶으신 분들을 위해 책도 구비되어있더라구요! 인테리어 너무예쁘고 휘낭시에 겉바속촉 너무맛있어요… 시그니처인 모크커피 적당히 달고 부드러워서 너무 좋았어요', 'ner_tags': {'MENU': [{'entity': '휘낭시에', 'descriptor': '겉바속촉이다', 'sentiment': '긍정'}, {'entity': '모크커피', 'descriptor': '적당히 달고 부드럽다', 'sentiment': '긍정'}], 'FACILITY': [{'entity': '인테리어', 'descriptor': '예쁘다', 'sentiment': '긍정'}], 'ATMOSPHERE': [{'entity': '따스한 분위기', 'descriptor': None, 'sentiment': '긍정'}, {'entity': '조용한 분위기', 'descriptor': None, 'sentiment': '긍정'}], 'TARGET': [{'entity': '독서', 'descriptor': None, 'sentiment': '긍정'}]}}, '12059': {'index': 12059, 'original_text': '내가 좋아하는 딸기라떼아이가 좋아하는 요거젤라또 씨리얼 초코베리믹스', 'ner_tags': {'MENU': [{'entity': '딸기라떼', 'descriptor': None, 'sentiment': '중립'}, {'entity': '요거젤라또', 'descriptor': None, 'sentiment': '중립'}, {'entity': '씨리얼 초코베리믹스', 'descriptor': None, 'sentiment': '중립'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7415': {'index': 7415, 'original_text': '더운 여름날 한입 크게 마시자마자얼음장같은 계곡에서 먹는 그 수박맛이 떠올랐어요더 이상의 수박은 없습니다. 꼭 먹어보세요 두번 먹으세요 초절세미녀사장님이 해주는 음료 먹으러꼭 한번 와요!', 'ner_tags': {'MENU': [{'entity': '수박', 'descriptor': '맛이 좋다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12062': {'index': 12062, 'original_text': '안녕하세요, 사장님이 이 리뷰를 꼭 보셨음 하네요.오후 10시 2분에 라면땅을 샀습니다. 홀에 손님이 저 포함 둘이었는데 라면땅 주문을 보시자, 한숨 푹푹 내쉬고 기다리는 내내 라면땅을 받으면 안됀다느니, 이것때문에 퇴근을 못한다느니 온갖 짜증은 다 내시는데 저 들으라고 하신걸까요?이럴거면 주문을 막아두셔야죠. 라스트 오더도 10시 30분이라던데 그럼 라스트 오더 시간은 왜 정하셨나요. 그전에 시켜도 이런데.제가 픽업대에 서있어도 투덜거리시길래 아무말 안하고 나오려다가 퇴근중이던 알바분께 말하니 그 분이 사과해주셨어요.정말 궁금합니다, 제가 뭘 그렇게 잘못해서 투덜거리며 꼽을 주시는지. 이게 잘못된 일이면 받을때 죄송하다고 할걸 그랬네요. 다른 분들은 이런 일 겪지않았으면합니다,번창하세요.', 'ner_tags': {'MENU': [{'entity': '라면땅', 'descriptor': '받지 못했다', 'sentiment': '부정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12063': {'index': 12063, 'original_text': '환승하기 전 아메리카노 한잔 마시기 좋습니다', 'ner_tags': {'MENU': [{'entity': '아메리카노', 'descriptor': None, 'sentiment': '중립'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7418': {'index': 7418, 'original_text': '원두 좋은거 쓰신다는데, 커피맛집이구요 여기 라떼도 맛있는데 가격도 저렴하고 양도 듬뿍이라 자주 가고 있어요', 'ner_tags': {'MENU': [{'entity': '라떼', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '커피', 'descriptor': '맛집이다', 'sentiment': '긍정'}, {'entity': '가격', 'descriptor': '저렴하다', 'sentiment': '긍정'}, {'entity': '양', 'descriptor': '듬뿍이다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7419': {'index': 7419, 'original_text': '저번엔 에이드를 먹고 오늘은 아메리카노 마셨는데 커피는 역시 잘 못마시겠어요 ㅜ 여기는 수제청 에이드라서 엄청 맛있었어요!', 'ner_tags': {'MENU': [{'entity': '에이드', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '아메리카노', 'descriptor': '잘 못마시겠어요', 'sentiment': '부정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2778': {'index': 2778, 'original_text': '봉천역에서부터 캘리 다녔습니다다행이 가까운 신림동으로 매장이전해서 또 따라 왔어요진짜 커피도 맛있고 크로플도 맛있어요저의 최애는 솔트카라멜라떼입니다어디에도 팔지 않고 캘리에서만 파는 진짜 개맛있는 커피입니다여기는 비비랑 숑숑이 강아지도 있는데 둘다 너무 귀여워요캘리 100번 추천합니다-!', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '크로플', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '솔트카라멜라떼', 'descriptor': '개맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '캘리', 'descriptor': '100번 추천한다', 'sentiment': '긍정'}]}}, '2780': {'index': 2780, 'original_text': '상주견 비비랑 숑숑이 너무 귀여워요 사장님께서 친절하시고 베이글 세트도 너무 맛있어요 서비스로 주신 샐러드도 맛있구요 ㅎㅅㅎ 강아지들 너무 귀엽고 동네 근처라서 종종 방문할 것 같아요', 'ner_tags': {'MENU': [{'entity': '베이글 세트', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '샐러드', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12064': {'index': 12064, 'original_text': '매장안에 테이블및좌석이 몇석 있어 간단히 먹고가긴좋습니당ㅎ 잠깐 앉아있는 사이 진짜 사람들 많이 오가시네요 점심시간이라그런지 알바분들 너무 고생이 많으세요.!', 'ner_tags': {'MENU': [], 'FACILITY': [{'entity': '테이블', 'descriptor': '몇석 있다', 'sentiment': '중립'}, {'entity': '좌석', 'descriptor': '몇석 있다', 'sentiment': '중립'}], 'ATMOSPHERE': [], 'TARGET': []}}, '7420': {'index': 7420, 'original_text': '아메리카노도 그렇고 이번에 먹어본 라떼도 그렇고 확실히 원두를 좋은걸 쓰는지 부드럽고 적당히 쌉싸름 한게 딱 제 스타일 이네요 이 가격에 이정도 퀄이라니 가까운 곳에 오픈해주셔서 감사합니다.', 'ner_tags': {'MENU': [{'entity': '아메리카노', 'descriptor': '부드럽고 적당히 쌉싸름하다', 'sentiment': '긍정'}, {'entity': '라떼', 'descriptor': '부드럽고 적당히 쌉싸름하다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7421': {'index': 7421, 'original_text': '강력츄천합니다고소하고 시원한 라때 한잔날도 더운데 오늘도 덕분에 시원하게 시작합니다.', 'ner_tags': {'MENU': [{'entity': '라떼', 'descriptor': '고소하고 시원하다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2781': {'index': 2781, 'original_text': '지나가는길에 신상카페가 있어 들러보았어요들어오자마자 귀여운 상주견 비비가 맞이해주었어요사장님께서도 완전 친절하시고 메뉴설명도 차근차근 해주셨구요1리터 사이즈도 가능해서 맛있는 음료를 배불리먹을수 있었어요그리고 서비스로 러스크를 디저트로 주셨는데, 맛있어서 허겁지겁먹느라 사진도 못남겼어요ㅠ그립톡도 인당 1개씩 받아서 추억 남기고갑니다.재방문의사 200% 입니다^~^', 'ner_tags': {'MENU': [{'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '재방문', 'descriptor': '의사 200%', 'sentiment': '긍정'}]}}, '12065': {'index': 12065, 'original_text': '누룽누룽 바삭 프라페 맛있네요 바삭바삭 씹히는게 구수합니다', 'ner_tags': {'MENU': [{'entity': '누룽누룽 바삭 프라페', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2779': {'index': 2779, 'original_text': '배달만 시켜먹다 너무 맛있어서 미팅을 여기로 잡고 직접 방문. 바로 먹으니 더 맛있음. 강아지 웰컴 플레이스라 너무 좋음. 비비 숑숑이 너무 귀여움. 가야 토스트 역대급 맛집임 전국 탑5 안에 듬. 다른 메뉴들도 맛있고 사장님을 위시해 사장님 가족들도 너무 친절하고 좋음. 방문도 단골해야겠음 끗', 'ner_tags': {'MENU': [{'entity': '비비 숑숑', 'descriptor': '너무 귀엽다', 'sentiment': '긍정'}, {'entity': '가야 토스트', 'descriptor': '역대급 맛집', 'sentiment': '긍정'}, {'entity': '다른 메뉴들', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '미팅', 'descriptor': None, 'sentiment': '긍정'}]}}, '2783': {'index': 2783, 'original_text': '포장해서 커피 마셨는데 너무 맛있어요', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7422': {'index': 7422, 'original_text': '공부하기전에 아아를 사가지고 가는데 오늘은 왜 시럽도 안넣었는데 단거죠! 왜죠! 넘 맛있어요', 'ner_tags': {'MENU': [{'entity': '아아', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '공부', 'descriptor': None, 'sentiment': '중립'}]}}, '2784': {'index': 2784, 'original_text': '소개를 받고 처음 찾아간 곳사장님 친절 하시고,가격대도 ㅋ. 꽃다발 구매 할 꽃집 없어 걱정.덜어 주셔서 감사합니다.사장님 또 뵐께요.', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7424': {'index': 7424, 'original_text': '맛은있는데 맛없는게 왜없는지모르겠네 치.', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12067': {'index': 12067, 'original_text': '버스정류장 바로 앞이라 테이크아웃하기 딱이에요', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '테이크아웃', 'descriptor': '딱이다', 'sentiment': '긍정'}]}}, '2782': {'index': 2782, 'original_text': '동네에 새로 생긴 카페가 있어 방문했어요! 4층에 위치해 있지만 입간판 덕분에 알게 됐네요. 라떼 마시러 왔다가 소이라떼도 같은 가격이길래 덕분에 저렴히 마셨습니다. 심지어 테이크아웃 시 대용량 아메리카노는 1900원으로 할인하고 있어요. 막 오픈했는지 그립톡도 주시고 과자도 주시고 굉장히 서비스가 좋고 친절하셔서 감사했어용!', 'ner_tags': {'MENU': [{'entity': '라떼', 'descriptor': '저렴하다', 'sentiment': '긍정'}, {'entity': '소이라떼', 'descriptor': '저렴하다', 'sentiment': '긍정'}, {'entity': '아메리카노', 'descriptor': '1900원으로 할인하다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7423': {'index': 7423, 'original_text': '바나나라떼랑 딸기라떼가 굉장히 굉장히 맛있고 건강해지는 느낌이였어요 가게 이모들 사다 줬는데 다들 너무 맛있다 해서 또 가서 카라멜 마끼아또 먹어봤는데 역시 또 맛있네요 맛있게 잘 먹었습니다. 아 사진은 제가 쫌 급하게 먹는 스타일이라 없습니다.', 'ner_tags': {'MENU': [{'entity': '바나나라떼', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '딸기라떼', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '카라멜 마끼아또', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12069': {'index': 12069, 'original_text': '더운여름에 좋아요!', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12068': {'index': 12068, 'original_text': '녹차 맛은 거의 안 나고 깔끔한 술 느낌.하지만 무알코올이라 나는 행복하지요~덕분에 합법 음주 수업을 듣는 중 ㅡㅂㅡ ㅎ', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [{'entity': '깔끔한 술 느낌', 'descriptor': None, 'sentiment': '중립'}], 'TARGET': []}}, '2786': {'index': 2786, 'original_text': '뭔가 비밀장소를 발견한 느낌입니다', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2785': {'index': 2785, 'original_text': '너무 더워서 젤라또 먹어봤어요.사진과 많이 다르네요ᆢ', 'ner_tags': {'MENU': [{'entity': '젤라또', 'descriptor': None, 'sentiment': '중립'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '12066': {'index': 12066, 'original_text': '가성비가 좋고 극장옆에 있어서 테이크아웃해서 가지고가면 좋습니다', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': [{'entity': '테이크아웃', 'descriptor': '좋다', 'sentiment': '긍정'}]}}, '12070': {'index': 12070, 'original_text': '가성비가 좋아요~!', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7425': {'index': 7425, 'original_text': '더워지니 아아로 마음을 달레요. 깨끗하고 청결한 카페는 맛도 일품이죠 이름걸고 하는 커피집은 품격도 일품이죠 동네에 이런 커피집있는게 정말다행ㅠ', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛이 일품이다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [{'entity': '카페', 'descriptor': '깨끗하고 청결하다', 'sentiment': '긍정'}], 'TARGET': []}}, '12071': {'index': 12071, 'original_text': '매장 너무 더러워요.', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '2787': {'index': 2787, 'original_text': '사장님 친절하시고 커피도 맛있고 샌드위치등 다 맛있어요~', 'ner_tags': {'MENU': [{'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}, {'entity': '샌드위치', 'descriptor': '맛있다', 'sentiment': '긍정'}], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}}, '7427': {'index': 7427, 'original_text': '주변 프렌차이즈 카페들 보다깔끔해서 자주 가는편 이에요!', 'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [{'entity': '깔끔하다', 'descriptor': None, 'sentiment': '긍정'}], 'TARGET': []}}, '2788': {'index': 2788, 'original_text': '소품이 예쁜 카페에요', 'ner_tags': {'MENU': [], 'FACIL

In [6]:
df = pd.read_csv("../data/shinline_cafe_reviews_test.csv")

In [14]:
df

,사업장명,place_id,리뷰내용,작성일
0,어반커피,12066484,2층에 있는 커피숍!! 내부는 깨끗하고 친구들과 수다 떨기 넘 좋아요!! 쿠키 프라...,25.12.27.
1,어반커피,12066484,내부 깨끗. 친절하시고 음료 넘넘 맛있어요~~ 특히 아이스푸딩크림라떼!!! 가격도...,25.12.27.
2,어반커피,12066484,"말렌카는 맛있었는데,,음료는 좀 아쉬웠어요ㅠㅠ메뉴에 그려져있던 체리블라썸이랑은 넘 ...",25.8.31.
3,어반커피,12066484,커피 음료 가격이 비싼편이라 그런가 한가로웠어요 인테리어 이쁘고 커피맛도 괜찮았지...,25.7.4.
4,어반커피,12066484,진짜 최악입니다 디저트 자체 맛은 괜찮았는데 매장 관리가 아예 안되고 있는듯 자리에...,25.6.7.
...,...,...,...,...
15228,매머드 익스프레스 신림대학점,1746293546,작은 사이즈 있어서 좋아요,22.2.20.
15229,매머드 익스프레스 신림대학점,1746293546,친절하시고 커피가 저렴해서 좋아요,22.2.7.
15230,매머드 익스프레스 신림대학점,1746293546,딸기 요거트 스무디가 진짜 존맛,22.1.29.
15231,매머드 익스프레스 신림대학점,1746293546,가격이 저렴하다고 커피 맛이 안좋다는 편견을 깨주는 브랜드입니다 ㅎㅎㅎ,21.12.25.
15232,매머드 익스프레스 신림대학점,1746293546,깔끔 친절 정확 굿!,21.12.22.

In [15]:
data

{'7406': {'index': 7406,
  'original_text': '#신림카페#사장님센스굿#레몬청#카페맛집#수제카페#먹스타그램#먹부림#갬성#인스타맛집직접 수제로 만든 청과 디저트라서 더 담백하고 새콤달콤해요. 맛 보시면 사장님 정성 다 느껴집니다ㅎ꼭 한번 방문해보세요^^',
  'ner_tags': {'MENU': [{'entity': '레몬청',
     'descriptor': '담백하고 새콤달콤하다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2767': {'index': 2767,
  'original_text': '커피가 연하고 맛있어용 ㅎ 강아지가 반겨줘요 ㅎ',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2766': {'index': 2766,
  'original_text': '사장님도 친절하시고 강아지랑 같이 왓는데 비숑들이 반겨줘서 좋앗습니다!맛잇어요~',
  'ner_tags': {'MENU': [{'entity': '맛',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '강아지', 'descriptor': '좋다', 'sentiment': '긍정'}]}},
 '2768': {'index': 2768,
  'original_text': '오늘도 만족합니다! 어제리뷰써서 서비스 샐러드 받아서 먹었는데 오 맛있더라구요 여자친구도 맛있다고 그러더라구요 그래서 조심스럽게 사장님에게 더받을수있냐고 여쭤봤는데 된다고 하셔서요ㅠ 감사합니다! 마지막은 귀여운 강아지들이 잘가라고 앞에까지 나오네요ㅎ',
  'ner_tags': {'MENU': [{'entity': '샐러드',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '여자친구',
     'descriptor': '맛있다고 하다',
     'sentiment': '긍정'}]}},
 '7407': {'index': 7407,
  'original_text': '쿠앤크케이크 먹어봤는데 너무 맛있어요 정말맛집이라서 맨날맨날 갈거에여',
  'ner_tags': {'MENU': [{'entity': '쿠앤크케이크',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12051': {'index': 12051,
  'original_text': '공사할때부터 기대했는데 가게 인테리어가 아늑하고 넘 예뻐요 모크커피 모크크림커피가 시그니처 메뉴인것같아서 마셔봤는데 너무맛있어서 비결이 뭐냐고 물어볼뻔했네요ㅠ 사장님도 친절하시고 넘좋아요 주말마다 가고싶어요',
  'ner_tags': {'MENU': [{'entity': '모크커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '모크크림커피', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [{'entity': '인테리어', 'descriptor': '아늑하다', 'sentiment': '긍정'}],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '주말마다 가고싶다',
     'descriptor': None,
     'sentiment': '긍정'}]}},
 '12050': {'index': 12050,
  'original_text': '시그니처가 커피는 커피대로 크림은 크림대로 맛있는데 둘의 하모니 최고. 적당히 달달해서 계속 들어감. 레몬머틀티는 향도 좋고 맛은 개인적으로 두번째 우렸을때가 더 맛있었습니다. 추울때 카페인 없는 음료로 아주 제격.',
  'ner_tags': {'MENU': [{'entity': '시그니처 커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '레몬머틀티', 'descriptor': '향이 좋다', 'sentiment': '긍정'},
    {'entity': '레몬머틀티', 'descriptor': '두번째 우렸을때 더 맛있다', 'sentiment': '긍정'},
    {'entity': '카페인 없는 음료', 'descriptor': '아주 제격이다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12052': {'index': 12052,
  'original_text': '카페가 완젼 귀여워요 ! 커피도 진하고 고소해서 디저트랑같이 먹으니까 넘 잘 어울려요! 사장님도 친절하시고~앞으로 자주 오게 될 거 같애요!',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '진하고 고소하다',
     'sentiment': '긍정'}],
   'FACILITY': [{'entity': '카페', 'descriptor': '귀엽다', 'sentiment': '긍정'}],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2769': {'index': 2769,
  'original_text': '오늘도 방문해서 러스크랑 샐러드 서비스 받았어요~자주방문할거같아요~!',
  'ner_tags': {'MENU': [{'entity': '러스크',
     'descriptor': None,
     'sentiment': '중립'},
    {'entity': '샐러드', 'descriptor': None, 'sentiment': '중립'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7408': {'index': 7408,
  'original_text': '#오레오#케이크#슬지로운생활오늘은 오레오케이크가 나왔다해서 먹어봤는데 안에 오레오 들어간 것도 많고 위에 오레오가 올라가있어서 맛있었어요 ㅎ',
  'ner_tags': {'MENU': [{'entity': '오레오케이크',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2771': {'index': 2771,
  'original_text': '가성비가 최고입니다 추천이요',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '7409': {'index': 7409,
  'original_text': '오레오 치즈케이크 신상이라고 해서 먹어봤는데 가격도 저렴라고 아메리카노랑 같이 먹으니까 너무 맛있네요 소량으로 판매하는게 아쉬워요 사장님 자주 만들어주세요~',
  'ner_tags': {'MENU': [{'entity': '오레오 치즈케이크',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '아메리카노', 'descriptor': None, 'sentiment': '중립'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '소량으로 판매하는게 아쉬워요',
     'descriptor': '아쉽다',
     'sentiment': '부정'}]}},
 '2770': {'index': 2770,
  'original_text': '1리터 아메리카노 테이크아웃이 1900원 이라길래 처음 방문했는데 진짜였어요!. 사장님도 친절하시고 처음방문한지라 러스크도 서비스로 주셨어요 커피도 맛있어요!. 가성비 굿',
  'ner_tags': {'MENU': [{'entity': '아메리카노',
     'descriptor': '가격이 1900원이다',
     'sentiment': '중립'},
    {'entity': '커피', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '가성비', 'descriptor': '굿', 'sentiment': '긍정'}]}},
 '7410': {'index': 7410,
  'original_text': '신상 오레오 치즈 케이크 먹어봤는데 5000원밖에 안하고 다른곳 케이크보다 싸고 양도 많고 입에 단맛이 남지 않아서 좋은거 같아요 일주일에 한두번 소량으로 판매하신다는데 메뉴판에 올라와있을때 바로 사 드세요ㅎ 언제 다 팔릴지 모릅니다!',
  'ner_tags': {'MENU': [{'entity': '오레오 치즈 케이크',
     'descriptor': '가격이 싸다',
     'sentiment': '긍정'},
    {'entity': '오레오 치즈 케이크', 'descriptor': '양이 많다', 'sentiment': '긍정'},
    {'entity': '오레오 치즈 케이크',
     'descriptor': '입에 단맛이 남지 않는다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12053': {'index': 12053,
  'original_text': "근처에 새로 생겨서 처음으로 가봤는데, Oh my gosh Is it a real?커피가 너무 맛있고 무엇보다 새로 오픈하셔서 매장도 깨끗하고, 좌석이 너무 편했어요! 가끔 카페에 가면 좌석이 불편해서 기분이 별로일때가 있는데, 좌석이 너무 편해서 여자친구랑 얘기하기에 너무좋았어요!조명도 간접조명이어서 눈도 편하고 제일 좋았던점은 first of all! It's the cafe owner! She is so kind and polite사장님이 너무 친절하셔서 그게 제일 좋았어요!",
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [{'entity': '매장', 'descriptor': '깨끗하다', 'sentiment': '긍정'},
    {'entity': '좌석', 'descriptor': '편하다', 'sentiment': '긍정'},
    {'entity': '조명', 'descriptor': '눈이 편하다', 'sentiment': '긍정'}],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '얘기하기', 'descriptor': '좋다', 'sentiment': '긍정'}]}},
 '7411': {'index': 7411,
  'original_text': '수박쥬스 너무 맛있어요~!동네에 카페가 많아서 근처 카페들을 탐방하러 갔다가 오랜만에 정말 마음에 드는 카페를 찾은 느낌이에요! 사장님도 센스도 있고 매장 분위기도 정말 좋아서 덕분에 잘 마시고 잘 쉬다가 가요!',
  'ner_tags': {'MENU': [{'entity': '수박쥬스',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [{'entity': '매장 분위기', 'descriptor': '좋다', 'sentiment': '긍정'}],
   'TARGET': []}},
 '7412': {'index': 7412,
  'original_text': '다른곳보다 저렴하고 맛있어서요즘 즐겨가는 카페입니다.ㅎ',
  'ner_tags': {'MENU': [],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '카페', 'descriptor': '저렴하고 맛있다', 'sentiment': '긍정'}]}},
 '12054': {'index': 12054,
  'original_text': '커피가 정말 맛있네요.! 풍미가 진하고 핸드메이드 디저트 류가 너무 맛있어요 ㅠ 가까우면 매일 가고 싶은 카페 당첨이에요 무조건! 따뜻하고 아늑한 분위기가 좋습니다 추천해요',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '핸드메이드 디저트 류', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [{'entity': '따뜻하고 아늑한 분위기',
     'descriptor': '좋다',
     'sentiment': '긍정'}],
   'TARGET': [{'entity': '카페', 'descriptor': '가고 싶다', 'sentiment': '긍정'}]}},
 '2773': {'index': 2773,
  'original_text': '사장님이 친절하고 커피가 저렴해요!',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '저렴하다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2774': {'index': 2774,
  'original_text': '항상 맛있어요매번 마시러 오는 캘리진짜 찐이에요강아지도 넘나 귀여워요',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '2772': {'index': 2772,
  'original_text': '사장님이 넘 친절하시고~커피랑 브런치가 고퀄리티 합니다갓구운 빵맛이 끝내줍니다 담에 가족들하고 외식하러와야겠어요',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '고퀄리티',
     'sentiment': '긍정'},
    {'entity': '브런치', 'descriptor': '고퀄리티', 'sentiment': '긍정'},
    {'entity': '빵', 'descriptor': '맛이 끝내준다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '가족들',
     'descriptor': '외식하러 와야겠다',
     'sentiment': '긍정'}]}},
 '7414': {'index': 7414,
  'original_text': '술지로운생활 너무 맛있어요! 여기만 갈거에요! 올여름은 슬지로운 생활!',
  'ner_tags': {'MENU': [{'entity': '술지로운생활',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7413': {'index': 7413,
  'original_text': '신메뉴 수박주스 시원하고 맛있네요 혼자 살아서 과일 사먹기 힘든데 종종 사먹을거 같아요',
  'ner_tags': {'MENU': [{'entity': '수박주스',
     'descriptor': '시원하고 맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '혼자', 'descriptor': None, 'sentiment': '중립'}]}},
 '12055': {'index': 12055,
  'original_text': '따뜻하고 귀여운 분위기가 너무 좋은 곳이였어요 시그니처 메뉴인 모크커피를 마셨는데 기분 좋은 달달함에 부드러운 우유와 진한 에스프레소가 어우러져 정말 순삭이였어요.당일 구우신 로투스피칸 휘낭시에는 겉은 바삭하고 안은 촉촉하니 버터향이 가득하여 정말 백개는 먹을 수 있을 정도였습니다… 앞으로 자주 갈게요! 모크커피 대박나세요!',
  'ner_tags': {'MENU': [{'entity': '모크커피',
     'descriptor': '기분 좋은 달달함에 부드러운 우유와 진한 에스프레소가 어우러져 순삭이다',
     'sentiment': '긍정'},
    {'entity': '로투스피칸 휘낭시네',
     'descriptor': '겉은 바삭하고 안은 촉촉하니 버터향이 가득하다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [{'entity': '따뜻하고 귀여운 분위기',
     'descriptor': '좋다',
     'sentiment': '긍정'}],
   'TARGET': []}},
 '12058': {'index': 12058,
  'original_text': '라떼가 진하고 맛있어요',
  'ner_tags': {'MENU': [{'entity': '라떼',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2775': {'index': 2775,
  'original_text': '저렴하고 양도 많고 간식도 무료로 주고 너무 좋습니다 추천합니다',
  'ner_tags': {'MENU': [],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '추천', 'descriptor': None, 'sentiment': '긍정'}]}},
 '2776': {'index': 2776,
  'original_text': '가격도 너무 저렴하고 맛있습니다 추천이요 ㅋ',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '12056': {'index': 12056,
  'original_text': '좌석도 많고 사장님 너무 친절하세요강아지들 먹을수있는 물통도 준비해더라고요!디저트랑 음료는 당연 맛있습니다',
  'ner_tags': {'MENU': [{'entity': '디저트',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [{'entity': '좌석', 'descriptor': '많다', 'sentiment': '긍정'},
    {'entity': '물통', 'descriptor': None, 'sentiment': '중립'}],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12061': {'index': 12061,
  'original_text': '맛있게 잘 마셨어요',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '7417': {'index': 7417,
  'original_text': '하루에 한잔 안먹으면 손이 떨려요.제발 가서 한잔만 드셔보세요^^ 다른곳 못갑니다장담해요 가격대비 가성비 굿굿굿#대학동커피#슬지로운생활#대학동맛집',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '12060': {'index': 12060,
  'original_text': '자주 가는 동네 까페, 커피, 음료가 맛있어서 좋아요',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7416': {'index': 7416,
  'original_text': '케이크 너무 맛있어요 음료도 너무 맛있구요!',
  'ner_tags': {'MENU': [{'entity': '케이크',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '음료', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2777': {'index': 2777,
  'original_text': '날이 좋아서 밖에서 먹으려고 포장했어요ㅎ샐러드도 서비스로 주시고 감사해요 남자친구가 커피입맛 까다로운데 깔끔하고 맛있대요 집 근처라 자주 방문할게요~',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '깔끔하고 맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '자주 방문', 'descriptor': None, 'sentiment': '긍정'}]}},
 '12057': {'index': 12057,
  'original_text': '따스한 분위기의 카페 조용히 독서하고싶으신 분들을 위해 책도 구비되어있더라구요! 인테리어 너무예쁘고 휘낭시에 겉바속촉 너무맛있어요… 시그니처인 모크커피 적당히 달고 부드러워서 너무 좋았어요',
  'ner_tags': {'MENU': [{'entity': '휘낭시에',
     'descriptor': '겉바속촉이다',
     'sentiment': '긍정'},
    {'entity': '모크커피', 'descriptor': '적당히 달고 부드럽다', 'sentiment': '긍정'}],
   'FACILITY': [{'entity': '인테리어', 'descriptor': '예쁘다', 'sentiment': '긍정'}],
   'ATMOSPHERE': [{'entity': '따스한 분위기', 'descriptor': None, 'sentiment': '긍정'},
    {'entity': '조용한 분위기', 'descriptor': None, 'sentiment': '긍정'}],
   'TARGET': [{'entity': '독서', 'descriptor': None, 'sentiment': '긍정'}]}},
 '12059': {'index': 12059,
  'original_text': '내가 좋아하는 딸기라떼아이가 좋아하는 요거젤라또 씨리얼 초코베리믹스',
  'ner_tags': {'MENU': [{'entity': '딸기라떼',
     'descriptor': None,
     'sentiment': '중립'},
    {'entity': '요거젤라또', 'descriptor': None, 'sentiment': '중립'},
    {'entity': '씨리얼 초코베리믹스', 'descriptor': None, 'sentiment': '중립'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7415': {'index': 7415,
  'original_text': '더운 여름날 한입 크게 마시자마자얼음장같은 계곡에서 먹는 그 수박맛이 떠올랐어요더 이상의 수박은 없습니다. 꼭 먹어보세요 두번 먹으세요 초절세미녀사장님이 해주는 음료 먹으러꼭 한번 와요!',
  'ner_tags': {'MENU': [{'entity': '수박',
     'descriptor': '맛이 좋다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12062': {'index': 12062,
  'original_text': '안녕하세요, 사장님이 이 리뷰를 꼭 보셨음 하네요.오후 10시 2분에 라면땅을 샀습니다. 홀에 손님이 저 포함 둘이었는데 라면땅 주문을 보시자, 한숨 푹푹 내쉬고 기다리는 내내 라면땅을 받으면 안됀다느니, 이것때문에 퇴근을 못한다느니 온갖 짜증은 다 내시는데 저 들으라고 하신걸까요?이럴거면 주문을 막아두셔야죠. 라스트 오더도 10시 30분이라던데 그럼 라스트 오더 시간은 왜 정하셨나요. 그전에 시켜도 이런데.제가 픽업대에 서있어도 투덜거리시길래 아무말 안하고 나오려다가 퇴근중이던 알바분께 말하니 그 분이 사과해주셨어요.정말 궁금합니다, 제가 뭘 그렇게 잘못해서 투덜거리며 꼽을 주시는지. 이게 잘못된 일이면 받을때 죄송하다고 할걸 그랬네요. 다른 분들은 이런 일 겪지않았으면합니다,번창하세요.',
  'ner_tags': {'MENU': [{'entity': '라면땅',
     'descriptor': '받지 못했다',
     'sentiment': '부정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12063': {'index': 12063,
  'original_text': '환승하기 전 아메리카노 한잔 마시기 좋습니다',
  'ner_tags': {'MENU': [{'entity': '아메리카노',
     'descriptor': None,
     'sentiment': '중립'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7418': {'index': 7418,
  'original_text': '원두 좋은거 쓰신다는데, 커피맛집이구요 여기 라떼도 맛있는데 가격도 저렴하고 양도 듬뿍이라 자주 가고 있어요',
  'ner_tags': {'MENU': [{'entity': '라떼',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '커피', 'descriptor': '맛집이다', 'sentiment': '긍정'},
    {'entity': '가격', 'descriptor': '저렴하다', 'sentiment': '긍정'},
    {'entity': '양', 'descriptor': '듬뿍이다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7419': {'index': 7419,
  'original_text': '저번엔 에이드를 먹고 오늘은 아메리카노 마셨는데 커피는 역시 잘 못마시겠어요 ㅜ 여기는 수제청 에이드라서 엄청 맛있었어요!',
  'ner_tags': {'MENU': [{'entity': '에이드',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '아메리카노', 'descriptor': '잘 못마시겠어요', 'sentiment': '부정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2778': {'index': 2778,
  'original_text': '봉천역에서부터 캘리 다녔습니다다행이 가까운 신림동으로 매장이전해서 또 따라 왔어요진짜 커피도 맛있고 크로플도 맛있어요저의 최애는 솔트카라멜라떼입니다어디에도 팔지 않고 캘리에서만 파는 진짜 개맛있는 커피입니다여기는 비비랑 숑숑이 강아지도 있는데 둘다 너무 귀여워요캘리 100번 추천합니다-!',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '크로플', 'descriptor': '맛있다', 'sentiment': '긍정'},
    {'entity': '솔트카라멜라떼', 'descriptor': '개맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '캘리',
     'descriptor': '100번 추천한다',
     'sentiment': '긍정'}]}},
 '2780': {'index': 2780,
  'original_text': '상주견 비비랑 숑숑이 너무 귀여워요 사장님께서 친절하시고 베이글 세트도 너무 맛있어요 서비스로 주신 샐러드도 맛있구요 ㅎㅅㅎ 강아지들 너무 귀엽고 동네 근처라서 종종 방문할 것 같아요',
  'ner_tags': {'MENU': [{'entity': '베이글 세트',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '샐러드', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12064': {'index': 12064,
  'original_text': '매장안에 테이블및좌석이 몇석 있어 간단히 먹고가긴좋습니당ㅎ 잠깐 앉아있는 사이 진짜 사람들 많이 오가시네요 점심시간이라그런지 알바분들 너무 고생이 많으세요.!',
  'ner_tags': {'MENU': [],
   'FACILITY': [{'entity': '테이블', 'descriptor': '몇석 있다', 'sentiment': '중립'},
    {'entity': '좌석', 'descriptor': '몇석 있다', 'sentiment': '중립'}],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7420': {'index': 7420,
  'original_text': '아메리카노도 그렇고 이번에 먹어본 라떼도 그렇고 확실히 원두를 좋은걸 쓰는지 부드럽고 적당히 쌉싸름 한게 딱 제 스타일 이네요 이 가격에 이정도 퀄이라니 가까운 곳에 오픈해주셔서 감사합니다.',
  'ner_tags': {'MENU': [{'entity': '아메리카노',
     'descriptor': '부드럽고 적당히 쌉싸름하다',
     'sentiment': '긍정'},
    {'entity': '라떼', 'descriptor': '부드럽고 적당히 쌉싸름하다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7421': {'index': 7421,
  'original_text': '강력츄천합니다고소하고 시원한 라때 한잔날도 더운데 오늘도 덕분에 시원하게 시작합니다.',
  'ner_tags': {'MENU': [{'entity': '라떼',
     'descriptor': '고소하고 시원하다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2781': {'index': 2781,
  'original_text': '지나가는길에 신상카페가 있어 들러보았어요들어오자마자 귀여운 상주견 비비가 맞이해주었어요사장님께서도 완전 친절하시고 메뉴설명도 차근차근 해주셨구요1리터 사이즈도 가능해서 맛있는 음료를 배불리먹을수 있었어요그리고 서비스로 러스크를 디저트로 주셨는데, 맛있어서 허겁지겁먹느라 사진도 못남겼어요ㅠ그립톡도 인당 1개씩 받아서 추억 남기고갑니다.재방문의사 200% 입니다^~^',
  'ner_tags': {'MENU': [{'entity': '음료',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '재방문', 'descriptor': '의사 200%', 'sentiment': '긍정'}]}},
 '12065': {'index': 12065,
  'original_text': '누룽누룽 바삭 프라페 맛있네요 바삭바삭 씹히는게 구수합니다',
  'ner_tags': {'MENU': [{'entity': '누룽누룽 바삭 프라페',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '2779': {'index': 2779,
  'original_text': '배달만 시켜먹다 너무 맛있어서 미팅을 여기로 잡고 직접 방문. 바로 먹으니 더 맛있음. 강아지 웰컴 플레이스라 너무 좋음. 비비 숑숑이 너무 귀여움. 가야 토스트 역대급 맛집임 전국 탑5 안에 듬. 다른 메뉴들도 맛있고 사장님을 위시해 사장님 가족들도 너무 친절하고 좋음. 방문도 단골해야겠음 끗',
  'ner_tags': {'MENU': [{'entity': '비비 숑숑',
     'descriptor': '너무 귀엽다',
     'sentiment': '긍정'},
    {'entity': '가야 토스트', 'descriptor': '역대급 맛집', 'sentiment': '긍정'},
    {'entity': '다른 메뉴들', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '미팅', 'descriptor': None, 'sentiment': '긍정'}]}},
 '2783': {'index': 2783,
  'original_text': '포장해서 커피 마셨는데 너무 맛있어요',
  'ner_tags': {'MENU': [{'entity': '커피',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7422': {'index': 7422,
  'original_text': '공부하기전에 아아를 사가지고 가는데 오늘은 왜 시럽도 안넣었는데 단거죠! 왜죠! 넘 맛있어요',
  'ner_tags': {'MENU': [{'entity': '아아',
     'descriptor': '맛있다',
     'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '공부', 'descriptor': None, 'sentiment': '중립'}]}},
 '2784': {'index': 2784,
  'original_text': '소개를 받고 처음 찾아간 곳사장님 친절 하시고,가격대도 ㅋ. 꽃다발 구매 할 꽃집 없어 걱정.덜어 주셔서 감사합니다.사장님 또 뵐께요.',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '7424': {'index': 7424,
  'original_text': '맛은있는데 맛없는게 왜없는지모르겠네 치.',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '12067': {'index': 12067,
  'original_text': '버스정류장 바로 앞이라 테이크아웃하기 딱이에요',
  'ner_tags': {'MENU': [],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': [{'entity': '테이크아웃', 'descriptor': '딱이다', 'sentiment': '긍정'}]}},
 '2782': {'index': 2782,
  'original_text': '동네에 새로 생긴 카페가 있어 방문했어요! 4층에 위치해 있지만 입간판 덕분에 알게 됐네요. 라떼 마시러 왔다가 소이라떼도 같은 가격이길래 덕분에 저렴히 마셨습니다. 심지어 테이크아웃 시 대용량 아메리카노는 1900원으로 할인하고 있어요. 막 오픈했는지 그립톡도 주시고 과자도 주시고 굉장히 서비스가 좋고 친절하셔서 감사했어용!',
  'ner_tags': {'MENU': [{'entity': '라떼',
     'descriptor': '저렴하다',
     'sentiment': '긍정'},
    {'entity': '소이라떼', 'descriptor': '저렴하다', 'sentiment': '긍정'},
    {'entity': '아메리카노', 'descriptor': '1900원으로 할인하다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '7423': {'index': 7423,
  'original_text': '바나나라떼랑 딸기라떼가 굉장히 굉장히 맛있고 건강해지는 느낌이였어요 가게 이모들 사다 줬는데 다들 너무 맛있다 해서 또 가서 카라멜 마끼아또 먹어봤는데 역시 또 맛있네요 맛있게 잘 먹었습니다. 아 사진은 제가 쫌 급하게 먹는 스타일이라 없습니다.',
  'ner_tags': {'MENU': [{'entity': '바나나라떼',
     'descriptor': '맛있다',
     'sentiment': '긍정'},
    {'entity': '딸기라떼', 'descriptor': '맛있다', 'sentiment': '긍정'},
    {'entity': '카라멜 마끼아또', 'descriptor': '맛있다', 'sentiment': '긍정'}],
   'FACILITY': [],
   'ATMOSPHERE': [],
   'TARGET': []}},
 '12069': {'index': 12069,
  'original_text': '더운여름에 좋아요!',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '12068': {'index': 12068,
  'original_text': '녹차 맛은 거의 안 나고 깔끔한 술 느낌.하지만 무알코올이라 나는 행복하지요~덕분에 합법 음주 수업을 듣는 중 ㅡㅂㅡ ㅎ',
  'ner_tags': {'MENU': [],
   'FACILITY': [],
   'ATMOSPHERE': [{'entity': '깔끔한 술 느낌',
     'descriptor': None,
     'sentiment': '중립'}],
   'TARGET': []}},
 '2786': {'index': 2786,
  'original_text': '뭔가 비밀장소를 발견한 느낌입니다',
  'ner_tags': {'MENU': [], 'FACILITY': [], 'ATMOSPHERE': [], 'TARGET': []}},
 '2785': {'index': 2785,
  'original_text': '너무 더워서 젤라또 먹어봤어요.사진과 많이 다르네요ᆢ',
  'ner_tags': {'MENU': [{'entity': '젤라또',
     'descriptor': None,

In [23]:
df_store = df
ner_data = data
import pandas as pd
import ast

# ------------------------------------------------------------------
# 데이터 결합 및 평탄화 (문자열 요소를 자동으로 감지하고 처리)
# ------------------------------------------------------------------
parsed_rows = []
target_categories = ['FACILITY', 'ATMOSPHERE', 'TARGET']

for str_idx, val in ner_data.items():
    target_idx = int(val['index'])
    
    if target_idx in df_store.index:
        store_name = df_store.loc[target_idx, '사업장명']
        ner_tags = val.get('ner_tags', {})
        
        for category in target_categories:
            items = ner_tags.get(category, [])
            
            if isinstance(items, list):
                for item in items:
                    if isinstance(item, str):
                        item = item.strip()
                        if item.startswith('{') and item.endswith('}'):
                            try:
                                item = ast.literal_eval(item)
                            except (ValueError, SyntaxError):
                                print(item)
                                continue # 변환 실패 시 패스
                        else:
                            # 케이스 B: 진짜 단순 단어 문자열일 때 (예: '콘센트')
                            parsed_rows.append({
                                '사업장명': store_name,
                                '키워드': item,          # 단어 자체를 키워드로 저장
                                'descriptor': '',       # 비어있으므로 공백 처리
                                'sentiment': ''         # 비어있으므로 공백 처리
                            })
                            continue
                    
                    # 케이스 C: 정상적으로 딕셔너리 형태로 저장되어 있거나 위의 변환이 성공했을 때
                    if isinstance(item, dict):
                        parsed_rows.append({
                            '사업장명': store_name,
                            '키워드': item.get('entity', ''),
                            'descriptor': item.get('descriptor', ''),
                            'sentiment': item.get('sentiment', '')
                        })

# ------------------------------------------------------------------
# 최종 데이터프레임 빌드
# ------------------------------------------------------------------
df_final = pd.DataFrame(parsed_rows)

In [27]:
df_final

                    사업장명        키워드 descriptor sentiment
0                카페캘리 본점        강아지         좋다        긍정
1                카페캘리 본점       여자친구    맛있다고 하다        긍정
2               ?커피,MOCC       인테리어       아늑하다        긍정
3               ?커피,MOCC  주말마다 가고싶다       None        긍정
4               ?커피,MOCC         카페        귀엽다        긍정
...                  ...        ...        ...       ...
10611               궁전다방       인테리어        멋지다        긍정
10612               궁전다방        화장실      호텔 같다        긍정
10613  Mono Hertz(모노헤르쯔)        화장실       깨끗하다        긍정
10614  Mono Hertz(모노헤르쯔)         내부    좌석 다양하다        긍정
10615  Mono Hertz(모노헤르쯔)         조명         좋다        긍정

[10616 rows x 4 columns]

In [35]:
list(df_final[df_final['사업장명'] == '카페캘리 본점']['키워드'])

['강아지',
 '여자친구',
 '가성비',
 '가족들',
 '추천',
 '자주 방문',
 '캘리',
 '재방문',
 '미팅',
 '애견동반',
 '귀여운 비숑 강아지들',
 '반려견 동반',
 '강아지',
 '카페']

In [30]:
df[df['사업장명'] == '카페캘리 본점']

,사업장명,place_id,리뷰내용,작성일
2762,카페캘리 본점,1712594911,강아지와 산책 후 너무 추워서 방문했더니 따뜻하고 신림천이 내려다 보이는 뷰가 너무...,25.12.14.
2763,카페캘리 본점,1712594911,서원역 근처 오며 가며 보다가 애견동반해서 처음 방문했는데 강아지가 좋아해서 뿌듯하...,25.9.14.
2764,카페캘리 본점,1712594911,귀여운 비숑 강아지들이 왕왕 반겨주는 카페에요~ 반려견 동반 가능합니다~ 브런치와 ...,25.7.12.
2765,카페캘리 본점,1712594911,강아지도 데려올 수 있네요 친절하시고 리얼수박 맛있어요,24.7.27.
2766,카페캘리 본점,1712594911,첫방문해서 '☕️아메리카노 1리터ㆍ카페라떼' 테이크아웃 다녀왔는데요~ 🧏사장님이 정...,24.4.27.
2767,카페캘리 본점,1712594911,사장님도 친절하시고 강아지랑 같이 왓는데 비숑들이 반겨줘서 좋앗습니다!맛잇어요~❤️,24.4.27.
2768,카페캘리 본점,1712594911,커피가 연하고 맛있어용 ㅎㅎ 강아지가 반겨줘요 ㅎ,24.4.13.
2769,카페캘리 본점,1712594911,오늘도 만족합니다! 어제리뷰써서 서비스 샐러드 받아서 먹었는데 오 맛있더라구요 여자...,24.4.13.
2770,카페캘리 본점,1712594911,오늘도 방문해서 러스크랑 샐러드 서비스 받았어요~~자주방문할거같아요~~~!,24.4.12.
2771,카페캘리 본점,1712594911,1리터 아메리카노 테이크아웃이 1900원 이라길래 처음 방문했는데 진짜였어요!. 사...,24.4.11.
2772,카페캘리 본점,1712594911,가성비가 최고입니다 추천이요,24.4.10.
2773,카페캘리 본점,1712594911,사장님이 넘 친절하시고~커피랑 브런치가 고퀄리티 합니다갓구운 빵맛이 끝내줍니다 담...,24.4.6.
2774,카페캘리 본점,1712594911,사장님이 친절하고 커피가 저렴해요!,24.3.24.
2775,카페캘리 본점,1712594911,항상 맛있어요매번 마시러 오는 캘리진짜 찐이에요강아지도 넘나 귀여워요,24.3.24.
2776,카페캘리 본점,1712594911,저렴하고 양도 많고 간식도 무료로 주고 너무 좋습니다 추천합니다,24.3.23.
2777,카페캘리 본점,1712594911,가격도 너무 저렴하고 맛있습니다 추천이요 ㅋㅋㅋ,24.3.21.
2778,카페캘리 본점,1712594911,날이 좋아서 밖에서 먹으려고 포장했어요ㅎㅎ샐러드도 서비스로 주시고 감사해요 남자친구...,24.3.10.
2779,카페캘리 본점,1712594911,봉천역에서부터 캘리 다녔습니다다행이 가까운 신림동으로 매장이전해서 또 따라 왔어요진...,24.2.21.
2780,카페캘리 본점,1712594911,배달만 시켜먹다 너무 맛있어서 미팅을 여기로 잡고 직접 방문. 바로 먹으니 더 맛있...,24.1.26.
2781,카페캘리 본점,1712594911,상주견 비비랑 숑숑이 너무 귀여워요💖 사장님께서 친절하시고 베이글 세트도 너무 맛있...,24.1.19.
2782,카페캘리 본점,1712594911,지나가는길에 신상카페가 있어 들러보았어요들어오자마자 귀여운 상주견 비비가 맞이해주었...,23.11.12.
2783,카페캘리 본점,1712594911,동네에 새로 생긴 카페가 있어 방문했어요! 4층에 위치해 있지만 입간판 덕분에 알게...,23.10.5.
2784,카페캘리 본점,1712594911,포장해서 커피 마셨는데 너무 맛있어요🩷,23.9.9.